### ISSUE TITLE
Zdejmowanie broni - Funkcja

### ISSUE THREAD

**Issue by Fakiron** [Fakiron/CalmGuardian#1]
W pliku main.cpp nie dziala funkcja `zdejmowanie_broni()`

**Comment by CacholaPL** [comment]
Nie ogarniam jeszcze trochę tego GitHuba :/

**Comment by Bravo555** [comment]
No problem, brah. Żaden z nas nie ogarnia prawdę mówiąc, sam mam doświadczenie w czynnym uzytkowaniu tak z tydzien czy dwa :v

**Comment by Bravo555** [comment]
Funkcja usunięta
